training:
  num_epochs: 50
  batch_size: 64
  learning_rate: 0.001
  num_workers: 0

paths:
  data: "./data"
  models: "./models"
  checkpoint_model: "" #./models/nnue_model_checkpoint.pth
  checkpoint_optimizer: "" #./models/optimizer_checkpoint.pth
